
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int ST = 22;
  public static final int NOTEQUAL = 19;
  public static final int LPAREN = 9;
  public static final int MINUS = 5;
  public static final int INT_ID = 32;
  public static final int RPAREN = 10;
  public static final int SEMICOLON = 15;
  public static final int COMMA = 17;
  public static final int CLASS = 25;
  public static final int PLUS = 4;
  public static final int QUOTE = 36;
  public static final int ASSIGN = 16;
  public static final int IF = 2;
  public static final int DOT = 3;
  public static final int ID = 33;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int EQUAL = 18;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int NULL = 24;
  public static final int VOID = 30;
  public static final int ERROR = 31;
  public static final int LBRACK = 11;
  public static final int TIMES = 6;
  public static final int LBRACE = 13;
  public static final int RBRACK = 12;
  public static final int WHILE = 7;
  public static final int CLASS_ID = 35;
  public static final int RBRACE = 14;
  public static final int EXTENDS = 26;
  public static final int STRING = 29;
  public static final int GTOREQUAL = 21;
  public static final int INTEGERR = 34;
  public static final int GT = 20;
  public static final int STOREQUAL = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "DOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "WHILE",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "ASSIGN",
  "COMMA",
  "EQUAL",
  "NOTEQUAL",
  "GT",
  "GTOREQUAL",
  "ST",
  "STOREQUAL",
  "NULL",
  "CLASS",
  "EXTENDS",
  "NEW",
  "RETURN",
  "STRING",
  "VOID",
  "ERROR",
  "INT_ID",
  "ID",
  "INTEGERR",
  "CLASS_ID",
  "QUOTE"
  };
}

